# Generated by Django 3.1 on 2020-08-04 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('identifiant', models.UUIDField(default=uuid.uuid4, help_text='Identifiant unique pour ce logement', primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Entre le nom du logement', max_length=200)),
                ('capacite', models.IntegerField(help_text='Entre la capacité maximum du logement')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('identifiant', models.UUIDField(default=uuid.uuid4, help_text='Identifiant unique pour cette reservation', primary_key=True, serialize=False)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.logement')),
            ],
            options={
                'ordering': ['debut', 'fin'],
            },
        ),
    ]
