# Generated by Django 3.1 on 2020-08-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200804_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logement',
            old_name='identifiant',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='identifiant',
            new_name='id',
        ),
    ]
