# Generated by Django 3.1 on 2020-08-04 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200804_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logement',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='uuid',
        ),
        migrations.AddField(
            model_name='logement',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.logement'),
        ),
    ]
