# Generated by Django 3.1 on 2020-08-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200804_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.logement'),
        ),
    ]
