# Generated by Django 3.1 on 2020-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200804_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Entre une question de la FAQ', max_length=1000)),
                ('reponse', models.TextField(help_text='Entre la reponse a la question', max_length=1000)),
            ],
        ),
    ]
