# Generated by Django 3.1 on 2020-08-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_questionreponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la photo', max_length=100)),
                ('image', models.ImageField(help_text='Insere la photo ici', upload_to='')),
                ('page_principale', models.BooleanField(help_text="True si l'image peut apparaitre en fond d'ecran, False sinon")),
                ('logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.logement')),
            ],
            options={
                'ordering': ['logement', 'nom'],
            },
        ),
        migrations.DeleteModel(
            name='QuestionReponse',
        ),
    ]
