# Generated by Django 3.1 on 2020-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200806_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Texte à copier/coller de fontawesome.com', max_length=100)),
                ('description', models.TextField(help_text='Description de la caracteristique (rester succinct)', max_length=300)),
                ('z_axis', models.IntegerField(help_text='Ordre selon lequel les caracteristique sont tries pour apparaitre sur la page (plusieur caracteristique peuvent avoir le meme z_axis)')),
            ],
            options={
                'ordering': ['z_axis'],
            },
        ),
    ]
