# Generated by Django 3.1 on 2020-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_caracteristique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristique',
            name='z_axis',
            field=models.IntegerField(default=0, help_text='Ordre selon lequel les caracteristique sont tries pour apparaitre sur la page (plusieur caracteristique peuvent avoir le meme z_axis)'),
        ),
    ]
