# Generated by Django 3.1 on 2020-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200807_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'option", max_length=20)),
                ('prix', models.IntegerField(default=0, help_text="Prix de l'option")),
                ('plusieurs', models.BooleanField(default=False, help_text='Cocher si le client peut en prendre plusieurs')),
            ],
            options={
                'ordering': ['nom', 'prix'],
            },
        ),
        migrations.AlterField(
            model_name='photographie',
            name='page_principale',
            field=models.BooleanField(help_text="Cocher si l'image peut apparaitre en fond d'ecran"),
        ),
    ]
