# Generated by Django 3.1 on 2020-08-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200808_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='nom',
            field=models.CharField(help_text="Nom de l'option (au singulier si plusieurs)", max_length=20),
        ),
    ]
