# Generated by Django 3.1 on 2020-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200808_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='maximum',
            field=models.IntegerField(default=1, help_text="Nombre d' 'object' disponible au maximum"),
        ),
    ]
