# Generated by Django 3.1 on 2020-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_option_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='prix',
            field=models.IntegerField(default=0, help_text='Prix de la nuit'),
        ),
    ]
