# Generated by Django 3.1 on 2020-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_logement_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du Calendrier extérieur (AirBnb, Booking, etc.)', max_length=20)),
                ('url', models.URLField(help_text="URL d'Export du calendrier")),
            ],
        ),
    ]
