# Generated by Django 3.1 on 2020-08-18 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_calendrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='logement',
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, help_text='Texte descriptif (e.g. Nom, mail, lien url vers la page de la reservation, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.calendrier'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifiant pour cette reservation, ne pas changer'),
        ),
    ]
