# Generated by Django 3.1 on 2020-08-18 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200818_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='uid',
            field=models.CharField(default=uuid.uuid4, help_text='Unique identifiant pour cette reservation, ne pas changer', max_length=100),
        ),
    ]
